name: Geniusworks
favicon: null
layout_spectrum: 0.6953469032887369
typography_spectrum: 0.1225102439057082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5917682240251452
  lightness: 0.3808117078151554
  saturation: 0.4930724373552948
  rhythmicContrast: 0.7413186402991414
purpose: []
